apiVersion: apps/v1
kind: Deployment 
metadata:
  name: starling-aerial-robotics-system 
spec:
  selector:
    matchLabels:
      app: starling-aerial-robotics-system 
  replicas: 1
  template:
    metadata:
      labels:
        app: starling-aerial-robotics-system 
    spec:
      hostNetwork: true
      shareProcessNamespace: true
      nodeSelector:
        name: master
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
        - name:  mongodb
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
        - name: spring-boot-backend
          image: oshia/starling-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: react-frontend
          image: oshia/starling-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
   

---
# ... Service YAML definition
apiVersion: v1                                               # API version
kind: Service                                                # Type of the kubernetes resource
metadata:
  name: starlingui-backend-service                             # Name of the kubernetes resource
  labels:                                                    # Labels that will be applied to this resource
    app: starlingui-backend
  namespace: starlingui-aerial-robotics-system
spec:
  type: NodePort                                             # The service will be exposed by opening a Port on each node and proxying it.
  ports:
    - port: 3000
      targetPort: 3000
  selector:                                                  # The service exposes Pods with label `app=starlingui-backend`
    app: starlingui-backend
