# ... Service YAML definition
apiVersion: v1                                               # API version
kind: Service                                                # Type of the kubernetes resource
metadata:
  name: starlingui-backend-service                             # Name of the kubernetes resource
  labels:                                                    # Labels that will be applied to this resource
    app: starlingui-backend
  namespace: starlingui-aerial-robotics-system
spec:
  type: NodePort                                             # The service will be exposed by opening a Port on each node and proxying it.
  ports:
    - port: 3000
      targetPort: 3000
  selector:                                                  # The service exposes Pods with label `app=starlingui-backend`
    app: starlingui-backend
