# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_run:
    branches: [ "develop" ]
  commit_comment:
    branches: [ "develop" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file StarlingUI-backend/pom.xml
      
    - name: start minikube
      id: minikube
      with:
        minikube-version: 1.24.0
        driver: docker
        container-runtime: containerd
        kubernetes-version: v1.22.3
        cpus: 2
        memory: 4000m
        cni: bridge
      uses: medyagh/setup-minikube@master
    # now you can run kubectl to see the pods in the cluster
    - name: kubectl get pods
      run: kubectl get pods -A
    - name: kubectl get nodes
      run: kubectl get nodes -A
      
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: oshia
        password: Oshia850315@010928
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: oshia/test:version1
